### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Sebclem** [Sebclem/ClaptrapBot#35]
- [ ] Check if guild is correct on webpage
- [ ] Add user icon
- [ ] Rebuild help system
- [ ] Anti flood stats
- [ ] og meta properties
- [ ] text message rank
